# Generated by Django 5.1.7 on 2025-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog_banner/'),
        ),
    ]
